docker_compose: install pass package
osism/ansible-collection-commons pull request #354
Opened 2022-05-27 09:27 UTC by berendt

This will solve the following issue:

error getting credentials - err: exit status 1, out: `Cannot autolaunch
D-Bus without X11 $DISPLAY`

Closes #353

Signed-off-by: Christian Berendt <berendt@osism.tech>

2022-05-27 13:22 UTC, osfrickler requested changes
I don't see how this could actually be related. Is there an upstream bug for this? Is it reproducible?

I don't think we should hardcode such a workaround without a note and a reference to an upstream issue.

2022-05-27 13:27 UTC, osfrickler commented
I found https://github.com/docker/compose-cli/issues/1656 but this also looks weird. There is no mention of `pass` being called anywhere in the code.

2022-05-30 05:35 UTC, osfrickler commented
> Probably this only affects Ubuntu 18.04.
> 
> [docker/docker-credential-helpers#60](https://github.com/docker/docker-credential-helpers/issues/60)

So do we still need to support that? If yes, can we make the installation version-specific?

2022-05-30 07:42 UTC, berendt commented
We currently have Focal in the roll as the smallest supported version. Then it can be closed.

I will add it in the troubleshooting documentation for completeness.

2022-05-30 07:45 UTC, berendt commented
Replaced by https://github.com/osism/documentation/pull/394

2022-05-30 07:45 UTC, closed without merging